spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-root.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:file:./h2/db;NON_KEYWORDS=USER
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true  # enables http://localhost:8080/h2-console
